import { useState } from 'react'
import { HypothesisState, PatchEdit } from '../api'

interface Props {
  hyp: HypothesisState
  isWinner: boolean
  raceStartedAt: number | null
  now: number
}

function StatusPill({ status }: { status: string }) {
  const map: Record<string, string> = {
    queued: 'bg-gray-700 text-gray-300',
    patching: 'bg-yellow-800 text-yellow-200',
    testing: 'bg-blue-800 text-blue-200 animate-pulse',
    passed: 'bg-green-700 text-green-100',
    failed: 'bg-red-800 text-red-200',
    patch_failed: 'bg-orange-800 text-orange-200',
    timeout: 'bg-purple-800 text-purple-200',
    error: 'bg-red-900 text-red-300',
  }
  const labels: Record<string, string> = {
    queued: 'Queued',
    patching: 'Patching…',
    testing: 'Running test…',
    passed: 'PASSED',
    failed: 'FAILED',
    patch_failed: 'PATCH FAILED',
    timeout: 'TIMEOUT',
    error: 'ERROR',
  }
  return (
    <span className={`text-xs font-bold px-2 py-0.5 rounded ${map[status] ?? 'bg-gray-700 text-gray-300'}`}>
      {labels[status] ?? status.toUpperCase()}
    </span>
  )
}

function DiffPreview({ patch }: { patch: PatchEdit[] }) {
  return (
    <div className="font-mono text-xs mt-2 rounded overflow-hidden border border-gray-700">
      {patch.map((edit, i) => (
        <div key={i}>
          {edit.find.split('\n').map((line, j) => (
            <div key={`f${j}`} className="bg-red-950/60 text-red-300 px-3 py-0.5 whitespace-pre">
              - {line}
            </div>
          ))}
          {edit.replace.split('\n').map((line, j) => (
            <div key={`r${j}`} className="bg-green-950/60 text-green-300 px-3 py-0.5 whitespace-pre">
              + {line}
            </div>
          ))}
        </div>
      ))}
    </div>
  )
}

function elapsed(startTs: number | null, endTs: number | null, now: number): string {
  if (!startTs) return ''
  const end = endTs ?? now / 1000
  const secs = Math.max(0, end - startTs)
  return secs < 60 ? `${secs.toFixed(1)}s` : `${Math.floor(secs / 60)}m ${Math.round(secs % 60)}s`
}

const RUNNING = new Set(['queued', 'patching', 'testing'])
const DONE = new Set(['passed', 'failed', 'patch_failed', 'timeout', 'error'])

export default function HypothesisCard({ hyp, isWinner, raceStartedAt, now }: Props) {
  const [showReasoning, setShowReasoning] = useState(false)
  const [showDiff, setShowDiff] = useState(false)
  const [showOutput, setShowOutput] = useState(false)

  const isRunning = RUNNING.has(hyp.status)
  const isDone = DONE.has(hyp.status)
  const isFailed = ['failed', 'patch_failed', 'timeout', 'error'].includes(hyp.status)
  const nowSecs = now / 1000

  const cardBorder = isWinner
    ? 'border-green-500 shadow-[0_0_20px_2px_rgba(34,197,94,0.35)]'
    : isFailed
    ? 'border-gray-700 opacity-70'
    : 'border-gray-700'

  return (
    <div className={`bg-gray-900 border-2 rounded-lg p-4 flex flex-col gap-3 relative transition-all ${cardBorder}`}>
      {/* Winner ribbon */}
      {isWinner && (
        <div className="absolute top-0 right-0 bg-green-500 text-black text-xs font-black px-3 py-1 rounded-bl-lg rounded-tr-lg">
          WINNER
        </div>
      )}

      {/* Dev badge */}
      {hyp.is_dev && (
        <span className="self-start text-xs bg-yellow-700 text-yellow-100 px-2 py-0.5 rounded font-bold">
          DEV PLACEHOLDER
        </span>
      )}
      {!hyp.is_dev && hyp.source === 'ibm-bob-subagent' && (
        <span className="self-start text-xs bg-blue-800 text-blue-100 px-2 py-0.5 rounded">
          Generated by IBM Bob subagent (session exported in <code>bob_sessions/</code>)
        </span>
      )}

      {/* Role + title */}
      <div>
        <p className="text-xs text-gray-400 font-medium uppercase tracking-wide">{hyp.role}</p>
        <p className="text-sm font-semibold text-white leading-snug mt-0.5">{hyp.title}</p>
        <p className="text-xs text-gray-500 mt-0.5">
          {hyp.suspected_file}:{hyp.suspected_line}
        </p>
      </div>

      {/* Confidence bar */}
      <div>
        <div className="flex justify-between text-xs text-gray-500 mb-1">
          <span>Confidence</span>
          <span>{Math.round(hyp.confidence * 100)}%</span>
        </div>
        <div className="h-1.5 bg-gray-800 rounded-full overflow-hidden">
          <div
            className="h-full bg-blue-500 rounded-full"
            style={{ width: `${hyp.confidence * 100}%` }}
          />
        </div>
      </div>

      {/* Status + timer */}
      <div className="flex items-center gap-3">
        <StatusPill status={hyp.status} />
        {(isRunning || isDone) && (
          <span className="text-xs text-gray-400 font-mono">
            {elapsed(hyp.started_at, hyp.finished_at, now)}
          </span>
        )}
      </div>

      {/* Collapsibles */}
      <div className="flex flex-col gap-1 text-xs">
        <button
          className="text-left text-gray-400 hover:text-gray-200"
          onClick={() => setShowReasoning(v => !v)}
        >
          {showReasoning ? '▾' : '▸'} Reasoning & evidence
        </button>
        {showReasoning && (
          <div className="bg-gray-800 rounded p-2 text-gray-300 leading-relaxed">
            <p>{hyp.reasoning}</p>
            {hyp.evidence.length > 0 && (
              <ul className="mt-1 list-disc list-inside text-gray-400">
                {hyp.evidence.map((e, i) => <li key={i}>{e}</li>)}
              </ul>
            )}
          </div>
        )}

        <button
          className="text-left text-gray-400 hover:text-gray-200"
          onClick={() => setShowDiff(v => !v)}
        >
          {showDiff ? '▾' : '▸'} Patch diff
        </button>
        {showDiff && <DiffPreview patch={hyp.patch} />}

        {isFailed && hyp.test_output && (
          <>
            <button
              className="text-left text-gray-400 hover:text-gray-200"
              onClick={() => setShowOutput(v => !v)}
            >
              {showOutput ? '▾' : '▸'} Test output
            </button>
            {showOutput && (
              <pre className="bg-gray-800 rounded p-2 text-red-300 text-xs overflow-x-auto whitespace-pre-wrap">
                {hyp.test_output}
              </pre>
            )}
          </>
        )}
      </div>
    </div>
  )
}
