import { useEffect, useState } from 'react'
import { api, ScenarioDetail, ScenarioSummary } from '../api'

interface Props {
  onRaceStarted: (runId: string, scenario: ScenarioDetail) => void
  onViewHistory: () => void
}

export default function IntakeView({ onRaceStarted, onViewHistory }: Props) {
  const [scenarios, setScenarios] = useState<ScenarioSummary[]>([])
  const [selectedId, setSelectedId] = useState('')
  const [detail, setDetail] = useState<ScenarioDetail | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    api.scenarios().then(s => {
      setScenarios(s)
      if (s.length > 0) setSelectedId(s[0].id)
    }).catch(() => setError('Failed to load scenarios'))
  }, [])

  useEffect(() => {
    if (!selectedId) return
    api.scenario(selectedId).then(d => {
      setDetail(d)
    }).catch(() => setError('Failed to load scenario'))
  }, [selectedId])

  async function startRace() {
    if (!detail) return
    setLoading(true)
    setError('')
    try {
      const { run_id } = await api.createRun(selectedId, detail.bug_report)
      onRaceStarted(run_id, detail)
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to start race')
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-gray-950 text-white flex flex-col">
      {/* Header */}
      <header className="border-b border-gray-800 px-8 py-5 flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-white">TriageRace</h1>
          <p className="text-gray-400 mt-1 text-sm">
            Four hypotheses. One real test. The fastest truth wins.
          </p>
        </div>
        <button
          className="bg-gray-800 hover:bg-gray-700 text-blue-400 px-4 py-2 rounded text-sm"
          onClick={onViewHistory}
        >
          📋 Race history
        </button>
      </header>

      <main className="flex-1 px-8 py-8 max-w-5xl w-full mx-auto flex flex-col gap-8">
        {error && (
          <div className="bg-red-900/40 border border-red-700 text-red-200 rounded px-4 py-3 text-sm">
            {error}
          </div>
        )}

        {/* Scenario selector */}
        <section>
          <label className="block text-sm font-medium text-gray-300 mb-2">Scenario</label>
          <select
            className="w-full bg-gray-900 border border-gray-700 rounded px-3 py-2 text-white text-sm focus:outline-none focus:border-blue-500"
            value={selectedId}
            onChange={e => setSelectedId(e.target.value)}
          >
            {scenarios.map(s => (
              <option key={s.id} value={s.id}>{s.title}</option>
            ))}
          </select>
        </section>

        {/* Bug report */}
        <section>
          <label className="block text-sm font-medium text-gray-300 mb-2">Bug Report</label>
          <textarea
            readOnly
            className="w-full bg-gray-900 border border-gray-700 rounded px-3 py-2 text-sm text-gray-100 font-mono focus:outline-none resize-y"
            rows={14}
            value={detail?.bug_report ?? ''}
          />
          <p className="mt-1 text-xs text-gray-500">
            The ticket IBM Bob's subagents read to produce the hypotheses below (pre-generated in the IDE). The race and tests run live.
          </p>
        </section>

        {/* What Bob understood */}
        {detail && detail.hypotheses.length > 0 && (
          <section>
            <h2 className="text-sm font-medium text-gray-300 mb-3">
              What Bob understood — {detail.hypotheses.length} hypotheses loaded
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {detail.hypotheses.map(h => (
                <div
                  key={h.id}
                  className="bg-gray-900 border border-gray-800 rounded p-3 flex flex-col gap-1"
                >
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-xs font-semibold text-gray-200">{h.role}</span>
                    {h.is_dev ? (
                      <span className="text-xs bg-yellow-700 text-yellow-100 px-2 py-0.5 rounded font-bold">
                        DEV PLACEHOLDER
                      </span>
                    ) : (
                      <span className="text-xs bg-blue-800 text-blue-100 px-2 py-0.5 rounded">
                        Generated by IBM Bob subagent
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-gray-400 leading-snug">{h.title}</p>
                </div>
              ))}
            </div>
            {detail.hypotheses.every(h => h.is_dev) && (
              <p className="mt-2 text-xs text-yellow-400">
                ⚠ These are dev placeholders. Run the real IBM Bob subagents (see <code>bob_prompts/subagent_prompts.md</code>) and delete the <code>_dev_*</code> files before recording the demo.
              </p>
            )}
          </section>
        )}

        {/* Start button */}
        <div>
          <button
            className="bg-blue-600 hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed text-white font-semibold px-8 py-3 rounded text-base transition-colors"
            onClick={startRace}
            disabled={loading || !detail}
          >
            {loading ? 'Starting…' : '🏁 Start the race'}
          </button>
        </div>
      </main>
    </div>
  )
}
